-- 既存データをクリア
DELETE FROM postworkplace;
DELETE FROM post;
DELETE FROM users;

-- ユーザーを作成
INSERT INTO users (id, nickname, age, gender, "planType", "createdAt", "updatedAt") VALUES
('user-1', 'testuser', 30, 'その他', 'free', NOW(), NOW());

-- postデータを作成
INSERT INTO post (id, "userId", "postType", state, lga, suburb, "createdAt", "updatedAt") VALUES
(1, 'user-1', 'Workplace', 'Victoria', 'Stonnington', 'Armadale', NOW(), NOW()),
(2, 'user-1', 'Workplace', 'New South Wales', 'Inner west', 'Townsville', NOW(), NOW()),
(3, 'user-1', 'Workplace', 'Queensland', 'Gold Coast', 'Gold Coast', NOW(), NOW()),
(4, 'user-1', 'Workplace', 'New South Wales', 'Woollahra', 'Macquarie', NOW(), NOW()),
(5, 'user-1', 'Workplace', 'New South Wales', 'Waverley', 'Braddon', NOW(), NOW()),
(6, 'user-1', 'Workplace', 'New South Wales', 'Randwick', 'Lyons', NOW(), NOW()),
(7, 'user-1', 'Workplace', 'New South Wales', 'Strathfield', 'Bonython', NOW(), NOW()),
(8, 'user-1', 'Workplace', 'New South Wales', 'Monash', 'Ngunnawal', NOW(), NOW()),
(9, 'user-1', 'Workplace', 'New South Wales', 'Kalamunda', 'Roseberry', NOW(), NOW()),
(10, 'user-1', 'Workplace', 'New South Wales', 'Coober Pedy', 'Westdale', NOW(), NOW()),
(11, 'user-1', 'Workplace', 'New South Wales', 'Woollahra', 'Tallwood', NOW(), NOW()),
(12, 'user-1', 'Workplace', 'New South Wales', 'Waverley', 'Paynes Crossing', NOW(), NOW()),
(13, 'user-1', 'Workplace', 'New South Wales', 'Randwick', 'Anembo', NOW(), NOW()),
(14, 'user-1', 'Workplace', 'New South Wales', 'Strathfield', 'North Willoughby', NOW(), NOW()),
(15, 'user-1', 'Workplace', 'New South Wales', 'Monash', 'Cranebrook', NOW(), NOW()),
(16, 'user-1', 'Workplace', 'New South Wales', 'Kalamunda', 'Girvan', NOW(), NOW()),
(17, 'user-1', 'Workplace', 'New South Wales', 'Coober Pedy', 'Caroona', NOW(), NOW()),
(18, 'user-1', 'Workplace', 'New South Wales', 'Woollahra', 'Towradgi', NOW(), NOW()),
(19, 'user-1', 'Workplace', 'New South Wales', 'Waverley', 'Coolabah', NOW(), NOW()),
(20, 'user-1', 'Workplace', 'New South Wales', 'Randwick', 'Maryland', NOW(), NOW()),
(21, 'user-1', 'Workplace', 'New South Wales', 'Strathfield', 'Eleebana', NOW(), NOW()),
(22, 'user-1', 'Workplace', 'New South Wales', 'Monash', 'Koolewong', NOW(), NOW()),
(23, 'user-1', 'Workplace', 'New South Wales', 'Kalamunda', 'Kilgra', NOW(), NOW()),
(24, 'user-1', 'Workplace', 'New South Wales', 'Coober Pedy', 'Sommariva', NOW(), NOW()),
(25, 'user-1', 'Workplace', 'New South Wales', 'Woollahra', 'Goomeribong', NOW(), NOW()),
(26, 'user-1', 'Workplace', 'New South Wales', 'Waverley', 'Closeburn', NOW(), NOW()),
(27, 'user-1', 'Workplace', 'New South Wales', 'Randwick', 'Degilbo', NOW(), NOW()),
(28, 'user-1', 'Workplace', 'New South Wales', 'Strathfield', 'Wongulla', NOW(), NOW()),
(29, 'user-1', 'Workplace', 'New South Wales', 'Monash', 'St Peters', NOW(), NOW()),
(30, 'user-1', 'Workplace', 'New South Wales', 'Kalamunda', 'Addison', NOW(), NOW()),
(31, 'user-1', 'Workplace', 'New South Wales', 'Coober Pedy', 'Manningham', NOW(), NOW()),
(32, 'user-1', 'Workplace', 'New South Wales', 'Woollahra', 'Oakbank', NOW(), NOW()),
(33, 'user-1', 'Workplace', 'New South Wales', 'Waverley', 'Magarey', NOW(), NOW()),
(34, 'user-1', 'Workplace', 'New South Wales', 'Randwick', 'Macgregor', NOW(), NOW()),
(35, 'user-1', 'Workplace', 'New South Wales', 'Strathfield', 'Braddon', NOW(), NOW()),
(36, 'user-1', 'Workplace', 'New South Wales', 'Monash', 'Lyons', NOW(), NOW()),
(37, 'user-1', 'Workplace', 'New South Wales', 'Kalamunda', 'Bonython', NOW(), NOW()),
(38, 'user-1', 'Workplace', 'New South Wales', 'Coober Pedy', 'Ngunnawal', NOW(), NOW()),
(39, 'user-1', 'Workplace', 'New South Wales', 'Woollahra', 'Roseberry', NOW(), NOW()),
(40, 'user-1', 'Workplace', 'New South Wales', 'Waverley', 'Westdale', NOW(), NOW()),
(41, 'user-1', 'Workplace', 'New South Wales', 'Randwick', 'Tallwood', NOW(), NOW()),
(42, 'user-1', 'Workplace', 'New South Wales', 'Strathfield', 'Paynes Crossing', NOW(), NOW()),
(43, 'user-1', 'Workplace', 'New South Wales', 'Monash', 'Anembo', NOW(), NOW()),
(44, 'user-1', 'Workplace', 'New South Wales', 'Kalamunda', 'North Willoughby', NOW(), NOW()),
(45, 'user-1', 'Workplace', 'New South Wales', 'Coober Pedy', 'Cranebrook', NOW(), NOW()),
(46, 'user-1', 'Workplace', 'New South Wales', 'Woollahra', 'Girvan', NOW(), NOW()),
(47, 'user-1', 'Workplace', 'New South Wales', 'Waverley', 'Caroona', NOW(), NOW()),
(48, 'user-1', 'Workplace', 'New South Wales', 'Randwick', 'Towradgi', NOW(), NOW()),
(49, 'user-1', 'Workplace', 'New South Wales', 'Strathfield', 'Coolabah', NOW(), NOW()),
(50, 'user-1', 'Workplace', 'New South Wales', 'Monash', 'Maryland', NOW(), NOW()),
-- 他のstateに少ないレコードを割り当て
(51, 'user-1', 'Workplace', 'Victoria', 'Vincent', 'Eleebana', NOW(), NOW()),
(52, 'user-1', 'Workplace', 'Queensland', 'Walkerville', 'Koolewong', NOW(), NOW()),
(53, 'user-1', 'Workplace', 'South Australia', 'Monash', 'Kilgra', NOW(), NOW()),
(54, 'user-1', 'Workplace', 'Western Australia', 'Randwick', 'Sommariva', NOW(), NOW()),
(55, 'user-1', 'Workplace', 'Tasmania', 'Kalamunda', 'Goomeribong', NOW(), NOW()),
(56, 'user-1', 'Workplace', 'Northern Territory', 'Coober Pedy', 'Closeburn', NOW(), NOW()),
(57, 'user-1', 'Workplace', 'Australian Capital Territory', 'Woollahra', 'Degilbo', NOW(), NOW()),
(58, 'user-1', 'Workplace', 'Victoria', 'Waverley', 'Wongulla', NOW(), NOW()),
(59, 'user-1', 'Workplace', 'Queensland', 'Whitehorse', 'St Peters', NOW(), NOW()),
(60, 'user-1', 'Workplace', 'South Australia', 'Prospect', 'Addison', NOW(), NOW()),
(61, 'user-1', 'Workplace', 'Western Australia', 'Strathfield', 'Manningham', NOW(), NOW()),
(62, 'user-1', 'Workplace', 'Tasmania', 'Vincent', 'Oakbank', NOW(), NOW()),
(63, 'user-1', 'Workplace', 'Northern Territory', 'Walkerville', 'Magarey', NOW(), NOW()),
(64, 'user-1', 'Workplace', 'Australian Capital Territory', 'Monash', 'Macquarie', NOW(), NOW()),
(65, 'user-1', 'Workplace', 'Victoria', 'Randwick', 'Macgregor', NOW(), NOW()),
(66, 'user-1', 'Workplace', 'Queensland', 'Kalamunda', 'Braddon', NOW(), NOW()),
(67, 'user-1', 'Workplace', 'South Australia', 'Coober Pedy', 'Lyons', NOW(), NOW()),
(68, 'user-1', 'Workplace', 'Western Australia', 'Woollahra', 'Bonython', NOW(), NOW()),
(69, 'user-1', 'Workplace', 'Tasmania', 'Waverley', 'Ngunnawal', NOW(), NOW()),
(70, 'user-1', 'Workplace', 'Northern Territory', 'Whitehorse', 'Roseberry', NOW(), NOW()),
(71, 'user-1', 'Workplace', 'Australian Capital Territory', 'Prospect', 'Westdale', NOW(), NOW()),
(72, 'user-1', 'Workplace', 'Victoria', 'Strathfield', 'Tallwood', NOW(), NOW()),
(73, 'user-1', 'Workplace', 'Queensland', 'Vincent', 'Paynes Crossing', NOW(), NOW()),
(74, 'user-1', 'Workplace', 'South Australia', 'Walkerville', 'Anembo', NOW(), NOW()),
(75, 'user-1', 'Workplace', 'Western Australia', 'Monash', 'North Willoughby', NOW(), NOW()),
(76, 'user-1', 'Workplace', 'Tasmania', 'Randwick', 'Cranebrook', NOW(), NOW()),
(77, 'user-1', 'Workplace', 'Northern Territory', 'Kalamunda', 'Girvan', NOW(), NOW()),
(78, 'user-1', 'Workplace', 'Australian Capital Territory', 'Coober Pedy', 'Caroona', NOW(), NOW()),
(79, 'user-1', 'Workplace', 'Victoria', 'Woollahra', 'Towradgi', NOW(), NOW()),
(80, 'user-1', 'Workplace', 'Queensland', 'Waverley', 'Coolabah', NOW(), NOW()),
(81, 'user-1', 'Workplace', 'South Australia', 'Whitehorse', 'Maryland', NOW(), NOW()),
(82, 'user-1', 'Workplace', 'Western Australia', 'Prospect', 'Eleebana', NOW(), NOW()),
(83, 'user-1', 'Workplace', 'Tasmania', 'Strathfield', 'Koolewong', NOW(), NOW()),
(84, 'user-1', 'Workplace', 'Northern Territory', 'Vincent', 'Kilgra', NOW(), NOW()),
(85, 'user-1', 'Workplace', 'Australian Capital Territory', 'Walkerville', 'Sommariva', NOW(), NOW()),
(86, 'user-1', 'Workplace', 'Victoria', 'Monash', 'Goomeribong', NOW(), NOW()),
(87, 'user-1', 'Workplace', 'Queensland', 'Randwick', 'Closeburn', NOW(), NOW()),
(88, 'user-1', 'Workplace', 'South Australia', 'Kalamunda', 'Degilbo', NOW(), NOW()),
(89, 'user-1', 'Workplace', 'Western Australia', 'Coober Pedy', 'Wongulla', NOW(), NOW()),
(90, 'user-1', 'Workplace', 'Tasmania', 'Woollahra', 'St Peters', NOW(), NOW()),
(91, 'user-1', 'Workplace', 'Northern Territory', 'Waverley', 'Addison', NOW(), NOW()),
(92, 'user-1', 'Workplace', 'Australian Capital Territory', 'Whitehorse', 'Manningham', NOW(), NOW()),
(93, 'user-1', 'Workplace', 'Victoria', 'Prospect', 'Oakbank', NOW(), NOW()),
(94, 'user-1', 'Workplace', 'Queensland', 'Strathfield', 'Magarey', NOW(), NOW()),
(95, 'user-1', 'Workplace', 'South Australia', 'Vincent', 'Macquarie', NOW(), NOW()),
(96, 'user-1', 'Workplace', 'Western Australia', 'Walkerville', 'Macgregor', NOW(), NOW()),
(97, 'user-1', 'Workplace', 'Tasmania', 'Monash', 'Braddon', NOW(), NOW()),
(98, 'user-1', 'Workplace', 'Northern Territory', 'Randwick', 'Lyons', NOW(), NOW()),
(99, 'user-1', 'Workplace', 'Australian Capital Territory', 'Kalamunda', 'Bonython', NOW(), NOW()),
(100, 'user-1', 'Workplace', 'Victoria', 'Coober Pedy', 'Ngunnawal', NOW(), NOW());

INSERT INTO postworkplace ("postId", wage, atmosphere, "recommendationLevel", comment, urls) VALUES
(1, 25.0, '{"Friendly","Professional"}', 4, 'Great place to work in Melbourne CBD.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg", "http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/2.jpeg"}'),
(2, 22.5, '{"Relaxed","Collaborative"}', 5, 'Amazing work environment in Geelong.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg", "http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/2.jpeg"}'),
(3, 20, '{"bad"}', 2, 'not really good.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg"}'),
(4, 23.0, '{"Dynamic","Innovative"}', 3, 'Good place with some challenges.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg"}'),
(5, 24.5, '{"Supportive","Friendly"}', 4, 'Nice team and environment.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg", "http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/2.jpeg"}'),
(6, 21.0, '{"Relaxed","Casual"}', 3, 'Decent work-life balance.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg", "http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/2.jpeg"}'),
(7, 26.0, '{"Professional","Efficient"}', 5, 'Highly recommend for career growth.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg", "http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/2.jpeg"}'),
(8, 22.0, '{"Collaborative","Friendly"}', 4, 'Great team spirit.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg", "http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/2.jpeg"}'),
(9, 23.5, '{"Innovative","Dynamic"}', 3, 'Challenging but rewarding.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg"}'),
(10, 24.0, '{"Friendly","Supportive"}', 4, 'Supportive management.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg", "http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/2.jpeg"}'),
(11, 24.0, '{"Casual"}', 3, 'Supportive management.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg", "http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/2.jpeg"}'),
(100, 25.0, '{"Professional","Efficient"}', 5, 'Excellent place to work.', '{"http://127.0.0.1:54321/storage/v1/object/public/waholi-base/post-images/workplace/1.jpeg"}');


-- データ挿入完了メッセージ
SELECT 'Seed data inserted successfully.' AS message;